steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/netlog-stream-template:v1', 'src/.']
  - name: gcr.io/cloud-builders/gcloud
    args: [ 'dataflow', 'flex-template', 'build', 'gs://${_BUCKET}/templates/netlog-stream.json', '--project=${PROJECT_ID}', '--image=gcr.io/${PROJECT_ID}/netlog-stream-template:v1', '--sdk-language=PYTHON', '--metadata-file=src/metadata.json'] 
  - name: gcr.io/cloud-builders/gcloud
    args: ['dataflow', 'flex-template', 'run', 'netlog-stream-job', '--template-file-gcs-location=gs://${_BUCKET}/templates/netlog-stream.json', '--max-workers=5', '--region=europe-west1', '--worker-machine-type=n1-standard-1', 
          '--enable-streaming-engine', '--parameters=topic=projects/${PROJECT_ID}/topics/${_TOPIC_NAME},qps=10000,sdk_container_image=gcr.io/${PROJECT_ID}/netlog-stream-template:v1,sdk_location=container']
substitutions:
  _TOPIC_NAME: netlog-stream
  _SUBSCRIPTION_ID: netlog-stream-sub
  _BUCKET: ${PROJECT_ID}-netlog-stream
  _DATASET_ID: "netlog_dataset"
  _TEMPLATE_IMAGE: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${TEMPLATE_NAME}/$netlog-stream-template:latest'
