steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/netlog-feature-template:${_TAG}', 'src/feature-pipeline/.']
  - name: gcr.io/cloud-builders/gcloud
    args: [ 'dataflow', 'flex-template', 'build', 'gs://${_BUCKET}/templates/tmp/netlog-feature.json', '--project=${PROJECT_ID}', '--image=gcr.io/${PROJECT_ID}/netlog-feature-template:${_TAG}', '--sdk-language=PYTHON', '--metadata-file=src/feature-pipeline/metadata.json'] 
  - name: gcr.io/cloud-builders/gcloud
    args: ['dataflow', 'flex-template', 'run', 'netlog-feature-job', '--template-file-gcs-location=gs://${_BUCKET}/templates/tmp/netlog-feature.json','--region=europe-west2', '--worker-machine-type=n1-standard-4','--num-workers=1','--max-workers=5']
images:
- 'gcr.io/${PROJECT_ID}/netlog-feature-template:${_TAG}'
substitutions:
  _BUCKET: "electric-armor-395015-netlog-bucket"
  _TAG: "354635"