steps:
  # - name: gcr.io/cloud-builders/gcloud
  #   args: ['pubsub', 'topics', 'create', '${_TOPIC_NAME}']
  # - name: gcr.io/cloud-builders/gcloud
  #   args: ['pubsub', 'subscriptions', 'create', '${_SUBSCRIPTION_ID}', '--topic', '${_TOPIC_NAME}']


  
      # - PROJECT_ID: $PROJECT_ID
      # - TOPIC_NAME: $_TOPIC_NAME

      #   gcloud app create --region=${_REGION} --project=${PROJECT_ID}
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}', '.']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}']

  #   args: ['mk', '-d', '--description', 'Network Flow Log Dataset', '--location=${LOCATION}', '${DATASET_ID}']
  # - name: gcr.io/cloud-solutions-images/bq
  #   args: ['mk', '-t', '--schema','aggr_log_table_schema.json',  '--time_partitioning_type=DAY', '--clustering_fields=dst_subnet,subscriber_id', '${PROJECT_ID}:${DATASET_ID}.cluster_model_data']
  # - name: gcr.io/cloud-solutions-images/bq
  #   args: ['mk', '-t', '--schema','aggr_log_table_schema.json',  '--time_partitioning_type=DAY', '--clustering_fields=dst_subnet,subscriber_id', '${PROJECT_ID}:${DATASET_ID}.cluster_model_data']
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['app', 'deploy', '${_SERVICE_NAME}','--image=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}','--region=${_REGION}','--platform=managed','--allow-unauthenticated',
  #          '--set-env-vars', "NUM_DEST_IP=2000,NUSERS=50000,AVG_REQUESTS_SECS=10,MAX_REQUEST_BYTES=5000,MIN_SESSION_EVENTS=5,MAX_SESSION_EVENTS=20,project_id=$PROJECT_ID,TOPIC_NAME=$_TOPIC_NAME"
  #         ]
#   - name: gcr.io/cloud-builders/gcloud
#     args: 
#       - app 
#       - deploy 
#       - app/app.yaml 
#       - '--project=${PROJECT_ID}'
#     env:
#       - PROJECT_ID=${PROJECT_ID}
#       - _TOPIC_NAME=${_TOPIC_NAME}
#       # - PROJECT_ID: $PROJECT_ID
#       # - TOPIC_NAME: $_TOPIC_NAME

#       #   gcloud app create --region=${_REGION} --project=${PROJECT_ID}
# # images:
# #   - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}'
substitutions:
#   # _IMAGE_NAME: netlog-stream
#   # _SERVICE_NAME: netlog-stream
  # _REGION: europe-west1
#   _TOPIC_NAME: netlog-stream-topic
#   # _SUBSCRIPTION_ID: netlog-stream-sub
  _TEMPLATE_IMAGE: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${TEMPLATE_NAME}/$netlog-stream-template:latest'
