runtime: python311
entrypoint: python3 -m stream_event_generator.py
# runtime_config:
#   runtime_version: 3.7
  # machine_type: e2-standard-2
env_variables:
  NUM_DEST_IP: 20000
  NUSERS: 500000
  AVG_REQUESTS_SECS: 10
  MAX_REQUEST_BYTES: 5000
  MIN_SESSION_EVENTS: 5
  MAX_SESSION_EVENTS: 20
  # PROJECT_ID: $PROJECT_ID
  # TOPIC_NAME: $_TOPIC_NAME